---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# abba

**abba** provides management of remote batch execution of programs into a cluster through a simple programming interface, and additional provide proper segregation of security identities via API abstraction.

<!-- badges: start -->
<!-- badges: end -->

-   Users can submit non-interactive jobs to run on Kubernetes
-   Non-interactive jobs can be sent to Kubernetes from Posit Connect
-   Jobs sent to Kubernetes from Posit Connect can be called through an R function 
-   Jobs sent to Kubernetes from Posit Connect can see R programs stored in a shared storage space.
-   While the job is running on Kubernetes, the submitting function monitors the job and waits for its completion
-   Upon completion of the job, the resulting log file is collected and is viewable
-   When executing from Posit Connect, the job is submitted using the kubectl utility locally
-   The kubectl utility on Posit Connect can only be run under a service account identity, and the user submitting the jobs cannot be modifed
-   The service account identity must be granted explicit access to files it may have to access

## Accessing the dev Kubernetes cluster

workbench-dev.atorusresearch.com

1. Ensure you have the cluster configured at ~/.kube/configured (Eli will do this)

2. Run jobs via `kubectl apply -f <file>` where file is your YAML file.

3. check jobs with `kubectl get jobs -n rstuido`

4. Get job output with `kubectl logs -n rstudio <jobname>`

## Explaining `inst/job.yaml` setup fields

| Placeholder          | Description |
|----------------------|-------------|
| `{job_name}`         | The name of the submitted job; user will give a recognizable and meaningful name upon the R function call. |
| `{generate_name}`    | The prefix of the name to be generated (in case you don't want to specify a static name); usually auto-generated. |
| `{user_tag}`         | Optional; can be specified by user to mark the job in some special way (i.e. "sdtm_batch"). |
| `{program_full_name}`| Full program name, including extension and full path. Should be specified by user. |
| `{program_base_name}`| Program name; auto-derived from `{program_full_name}`. |
| `{service_user}`     | A username of account with elevated privileges. This isn't something that needs to be exposed to a user. |
| `{cpu_limit}`        | A number of CPUs available to use for this Job. Could be 1 or 2. |
| `{memory_limit}`     | An amount of memory available for this Job in MBs. Possible options: 256, 512, 1024. |


