kind: Job
apiVersion: batch/v1
metadata:
  # User will give a recognizable and meaningful name upon the R function call.
  name: {job_name}
  # A service R function will generate UUID to be put here.
  generateName: {generate_name}
  namespace: rstudio
  labels:
    app.kubernetes.io/managed-by: Connect
  annotations:
    batch.kubernetes.io/job-tracking: ''
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 0
  selector:
  template:
    metadata:
      # As we run 1 Pod at a time, there is no need to specify a different name.
      generateName: {generate_name}
      creationTimestamp: null
      labels:
        job-name: {job_name}
      annotations:
        # Not sure if these matter?
        USER_TAG_0: {user_tag}
        name: {program_base_name}
        service_ports: '[]'
        stdin: ''
        user: {service_user}
    spec:
      volumes:
        # I assume this will have to be set to the home directory of the service account
        - name: mount0
          nfs:
            server: 10.14.0.6
            path: /home/{service_user}
      containers:
        - name: rs-launcher-container
          image: atoruscontainers.azurecr.io/jammy-1.0.1-workbench
          command:
            - /bin/bash
          args:
            - '-c'
            # This will have to point to the proper program to execute
            - cd ~ && R --slave --no-save --no-restore -f ~/rmd-plus-k8s/{program_full_name}
          env:
            - name: HOME
              value: /home/{service_user}
          resources:
            limits:
              cpu: '{cpu_limit}'
              memory: {memory_limit}M
          volumeMounts:
            # This will need to be configured
            - name: mount0
              mountPath: /home/{service_user}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          stdinOnce: true
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      shareProcessNamespace: true
      securityContext:
        # These will need to be autoset
        runAsUser: 1182601113
        runAsGroup: 1182600513
      schedulerName: default-scheduler
  completionMode: NonIndexed
  suspend: false
