#' Submit programs for execution in parallel. Each program in a list will be submitted
#' at the same time.
#'
#' @param prog_list A list of R program paths to execute
#' @param submit_func function that will be used to submit jobs
#' @param wait_func function that checks job status and returns when job finishes executing
#' @param ... arguments that will be passed to submit_func and wait_func functions
#'
#' @return list job IDs associated with executed programs
#' @noRd
#'
#' @examples \dontrun{
#' job_ids <- batch_submit_parallel(
#'   c("/mnt/work_drive/proj/comp/prot/task/development/prod/program/tfl/t1_dm.sas",
#'     "/mnt/work_drive/proj/comp/prot/task/development/prod/program/tfl/t1_ae.sas"))
#'  }
batch_submit_parallel <- function(prog_list,
                                  submit_func=abba_rslauncher_submit_job_local,
                                  wait_func=abba_rslauncher_watch_job_local,
                                  ...) {
  # Submit jobs for the programs and wait until everything has been executed
  job_ids <- sapply(prog_list, function(x) submit_func(x, ...))

  # wait until all programs finish executing
  results <- wait_func(job_ids, ...)

  # return job ids generated by submitting programs for execution in workbench
  return(job_ids)
}

#' Submit programs for execution in order defined by structure of input list.
#' Programs inside sublists will be executed in parallel, and sublists themself
#' would be submitted sequentially.
#'
#' @param prog_list A list of R program paths to execute
#' @param sequential when sequential=TRUE, prog_list is flattened and everything is executed sequentially.
#' @param submit_func function that will be used to submit jobs
#' @param wait_func function that checks job status and returns when job finishes executing
#' @param ... arguments that will be passed to submit_func and wait_func functions
#'
#' @return list job IDs associated with executed programs
#' @noRd
#'
#' @examples \dontrun{
#' job_ids <- submit_workbench_batch(list(
#'   c("/mnt/work_drive/proj/comp/prot/task/development/prod/program/sdtm/dm.sas"),
#'   c("/mnt/work_drive/proj/comp/prot/task/development/prod/program/sdtm/ae.sas"),
#'   c("/mnt/work_drive/proj/comp/prot/task/development/prod/program/tfl/t1_dm.sas",
#'     "/mnt/work_drive/proj/comp/prot/task/development/prod/program/tfl/t1_ae.sas")))
#'  }
abba_submit_batch <- function(prog_list,
                              sequential=FALSE,
                              submit_func=abba_rslauncher_submit_job_local,
                              wait_func=abba_rslauncher_watch_job_local,
                              ...) {

  # if prog_list is a data frame - convert it to a list of vectors according to set rules
  prog_list_converted <- dataframe_to_batch_list(prog_list)

  # if sequential=TRUE is specified - flatten the list and this will execute everything sequentially
  # REGARDLESS of whether prog_list is a list, a character vector or a data frame
  if (sequential==TRUE){
    prog_list_converted <- unlist(prog_list_converted)
  }
  # execute each item in the prog_list sequentially. Programs inside each list element,
  # which can also be a vector of program paths, will be executed in parallel
  job_ids <- list()
  previous_run_ok <- TRUE
  for (parallel_run in prog_list_converted){

    if (!all(previous_run_ok)){
      warning(sprintf("Programs %s have errors in their logs. Batch execution halted.", paste(previous_run_programs[!previous_run_ok], collapse=', ')))
      break
    }
    new_run <- batch_submit_parallel(parallel_run,
                                     submit_func=submit_func,
                                     wait_func=wait_func,
                                     ...)
    job_ids <- c(job_ids, new_run)
    previous_run_ok <- abba_rslauncher_get_job_succeeded_local(new_run)
    previous_run_programs <- parallel_run
  }

  return(unlist(job_ids))
}
