batch_submit_series <- function(prog_list, ...) {
  # submit all programs to execute one by one
  job_ids <- sapply(prog_list, submit_workbench_job, wait=TRUE, ...)
  # return job ids generated by submitting programs for execution in workbench
  return(job_ids)
}

batch_submit_parralel <- function(prog_list, ...) {
  # Submit jobs for the programs and wait until everything has been executed
  job_ids <- sapply(prog_list, function(x) submit_workbench_job(x, wait=FALSE))

  # wait untill all programs finish executing
  job_ids <- wait_for_workbench_job_completion(job_ids)

  # return job ids generated by submitting programs for execution in workbench
  return(job_ids)
}

submit_workbench_batch <- function(prog_list, ...) {
  # THIS IS A PLACEHOLDER FOR COMPLETE batch execution function
  return(batch_submit_parralel(prog_list, ...))
}
