#' Submit programs for execution in parallel. Each program in a list will be submitted
#' at the same time.
#'
#' @param prog_list A list of R program paths to execute
#' @param submit_func function that will be used to submit jobs
#' @param wait_func function that checks job status and returns when job finishes executing
#' @param ... arguments that will be passed to submit_func and wait_func functions
#'
#' @return list job IDs associated with executed programs
#' @noRd
#'
#' @examples \dontrun{
#' job_ids <- batch_submit_parallel(
#'   c("/mnt/work_drive/proj/comp/prot/task/development/prod/program/tfl/t1_dm.sas",
#'     "/mnt/work_drive/proj/comp/prot/task/development/prod/program/tfl/t1_ae.sas"))
#'  }
batch_submit_parallel <- function(prog_list,
                                  submit_func=abba_rslauncher_submit_job_local,
                                  wait_func=abba_rslauncher_watch_job_local,
                                  ...) {
  # Submit jobs for the programs and wait until everything has been executed
  job_ids <- sapply(prog_list, function(x) submit_func(x, ...))

  # wait until all programs finish executing
  results <- wait_func(job_ids, ...)

  # return job ids generated by submitting programs for execution in workbench
  return(job_ids)
}

#' Submit programs for execution in order defined by structure of input list.
#' Programs inside sublists will be executed in parallel, and sublists themself
#' would be submitted sequentially.
#'
#' @param prog_list A list of R program paths to execute
#' @param sequential when sequential=TRUE, prog_list is flattened and everything is executed sequentially.
#' @param submit_func function that will be used to submit jobs
#' @param wait_func function that checks job status and returns when job finishes executing
#' @param ... arguments that will be passed to submit_func and wait_func functions
#'
#' @return list job IDs associated with executed programs
#' @export
#'
#' @examples \dontrun{
#' job_ids <- abba_submit_batch(list(
#'   c("/mnt/work_drive/proj/comp/prot/task/development/prod/program/sdtm/dm.sas"),
#'   c("/mnt/work_drive/proj/comp/prot/task/development/prod/program/sdtm/ae.sas"),
#'   c("/mnt/work_drive/proj/comp/prot/task/development/prod/program/tfl/t1_dm.sas",
#'     "/mnt/work_drive/proj/comp/prot/task/development/prod/program/tfl/t1_ae.sas")))
#'  }
abba_submit_batch <- function(prog_list,
                              sequential=FALSE,
                              submit_func=abba_rslauncher_submit_job_local,
                              wait_func=abba_rslauncher_watch_job_local,
                              col_name='run_group',
                              ...) {

  # if sequential=TRUE is specified - flatten the list and this will execute everything sequentially
  # REGARDLESS of whether prog_list is a list, a character vector or a data frame
  if (sequential==TRUE){
    prog_list_converted <- unlist(dataframe_to_batch_list(prog_list))
  }
  else {prog_list_converted <- prog_list}

  # execute each item in the prog_list_converted sequentially. Programs inside
  # each list element, which can also be a vector of program paths,
  # will be executed in parallel, unless 'sequential=TRUE' is specified
  job_ids <- list()
  previous_run_ok <- TRUE
  previous_run_programs <- c()
  unique_run_groups <- get_run_groups(prog_list)

  for (rg in unique_run_groups){
    # check if programs from previous run group were executed completely
    batch_check_results <-
      batch_run_control(prog_list_converted,
                        current_group=rg,
                        previous_run_programs=previous_run_programs,
                        previous_run_ok=previous_run_ok,
                        col_name='run_group',
                        ...)

    prog_list_converted <- batch_check_results$prog_list

    # if batch input is a list, do not run the next group
    if (batch_check_results$stop == TRUE){break}

    # select programs for running in parallel
    parallel_run <- select_parallel_run(prog_list_converted, rg, col_name=col_name)
    message(sprintf("Submitting programs for parallel run:\n\t%s",
                    paste(parallel_run, collapse='\n\t')))
    # submit the run
    new_run <- batch_submit_parallel(parallel_run,
                                     submit_func=submit_func,
                                     wait_func=wait_func,
                                     ...)
    # add executed jobs to the list
    job_ids <- c(job_ids, new_run)
    # collect information about this run group exit codes to decide if we should
    # continue with the batch run on the next loop
    previous_run_ok <- abba_rslauncher_get_job_succeeded_local(new_run)
    previous_run_programs <- parallel_run
  }

  return(unlist(job_ids))
}
